# -*- coding: utf-8 -*-
"""Streamflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFtK-OtYAsOJNYmtSNMh7v4lfPS86xFE
"""

# ==========================================
# STREAMFLOW CUSTOMER CHURN ANALYSIS
# Pandas + NumPy
# ==========================================

import pandas as pd
import numpy as np

# ==========================================
# LOAD DATASETS
# ==========================================

customers = pd.read_csv(
    "/streamflow_customers.csv",
    low_memory=False
)

subscriptions = pd.read_csv(
    "/streamflow_subscriptions.csv",
    low_memory=False
)

usage = pd.read_csv(
    "/streamflow_usage_metrics.csv",
    low_memory=False
)

support = pd.read_csv(
    "/streamflow_support_tickets.csv",
    low_memory=False
)

# ==========================================
# DATA CLEANING
# ==========================================

customers['signup_date'] = pd.to_datetime(
    customers['signup_date'],
    dayfirst=True,
    errors='coerce'
)

subscriptions['start_date'] = pd.to_datetime(
    subscriptions['start_date'],
    format='%Y-%m-%d',
    errors='coerce'
)

subscriptions['end_date'] = pd.to_datetime(
    subscriptions['end_date'],
    format='%Y-%m-%d',
    errors='coerce'
)


# ==========================================
# OVERALL KPIs
# ==========================================

total_customers = customers['customer_id'].nunique()

churned_customers = subscriptions[
    subscriptions['status'] == 'CHURNED'
]['customer_id'].nunique()

churn_rate = (
    churned_customers / total_customers
) * 100

total_revenue = subscriptions[
    'monthly_price'
].sum()

avg_subscription_price = subscriptions[
    'monthly_price'
].mean()

revenue_lost = subscriptions[
    subscriptions['status'] == 'CHURNED'
]['monthly_price'].sum()

print("="*50)
print("OVERALL KPIs")
print("="*50)

print("Total Customers :", total_customers)
print("Churned Customers :", churned_customers)
print("Churn Rate :", round(churn_rate,2), "%")
print("Total Revenue : $", round(total_revenue,2))
print("Average Subscription Price : $",
      round(avg_subscription_price,2))
print("Revenue Lost Due To Churn : $",
      round(revenue_lost,2))

# ==========================================
# CHURN BY SUBSCRIPTION TYPE
# ==========================================

subscription_analysis = (
    subscriptions
    .groupby('subscription_type')
    .agg(
        customers=('customer_id','count'),
        churned=('status',
                 lambda x:(x=='CHURNED').sum())
    )
)

subscription_analysis['churn_rate'] = (
    subscription_analysis['churned']
    /
    subscription_analysis['customers']
)*100

print("\n")
print("="*50)
print("CHURN BY SUBSCRIPTION TYPE")
print("="*50)

print(subscription_analysis)

# ==========================================
# CHURN BY COUNTRY
# ==========================================

country_data = pd.merge(
    customers,
    subscriptions,
    on='customer_id'
)

country_analysis = (
    country_data
    .groupby('country')
    .agg(
        customers=('customer_id','count'),
        churned=('status',
                 lambda x:(x=='CHURNED').sum())
    )
)

country_analysis['churn_rate'] = (
    country_analysis['churned']
    /
    country_analysis['customers']
)*100

print("\n")
print("="*50)
print("CHURN BY COUNTRY")
print("="*50)

print(country_analysis)

# ==========================================
# CUSTOMER SEGMENT ANALYSIS
# ==========================================

segment_data = pd.merge(
    customers,
    usage,
    on='customer_id'
)

segment_analysis = (
    segment_data
    .groupby('customer_tier')
    .agg(
        customers=('customer_id','count'),
        avg_engagement=('engagement_score','mean'),
        avg_sessions=('num_sessions','mean'),
        avg_hours=('total_hours_watched','mean')
    )
)

print("\n")
print("="*50)
print("CUSTOMER SEGMENTS")
print("="*50)

print(segment_analysis)

# ==========================================
# ACQUISITION CHANNEL ANALYSIS
# ==========================================

channel_data = pd.merge(
    customers,
    subscriptions,
    on='customer_id'
)

channel_analysis = (
    channel_data
    .groupby('acquisition_channel')
    .agg(
        customers=('customer_id','count'),
        revenue=('monthly_price','sum')
    )
)

print("\n")
print("="*50)
print("ACQUISITION CHANNEL ANALYSIS")
print("="*50)

print(channel_analysis)

# ==========================================
# DEVICE ANALYSIS
# ==========================================

device_analysis = (
    customers
    .groupby('device_type')
    .agg(
        customers=('customer_id','count')
    )
    .sort_values(
        by='customers',
        ascending=False
    )
)

print("\n")
print("="*50)
print("DEVICE ANALYSIS")
print("="*50)

print(device_analysis)

# ==========================================
# CHURN REASON ANALYSIS
# ==========================================

churn_reason_analysis = (
    subscriptions[
        subscriptions['status']=='CHURNED'
    ]
    .groupby('churn_reason')
    .agg(
        churned_customers=('customer_id','count')
    )
    .sort_values(
        by='churned_customers',
        ascending=False
    )
)

print("\n")
print("="*50)
print("TOP CHURN REASONS")
print("="*50)

print(churn_reason_analysis)

# ==========================================
# USAGE METRICS
# ==========================================

print("\n")
print("="*50)
print("USAGE INSIGHTS")
print("="*50)

print(
    "Average Usage Hours :",
    round(
        usage['total_hours_watched'].mean(),
        2
    )
)

print(
    "Average Session Length :",
    round(
        usage['avg_session_length_min'].mean(),
        2
    )
)

print(
    "Average Sessions :",
    round(
        usage['num_sessions'].mean(),
        2
    )
)

print(
    "Average Engagement Score :",
    round(
        usage['engagement_score'].mean(),
        2
    )
)

print("\nAnalysis Completed Successfully.")

"""**VISUALIZATION**

**1. Churn Rate by Subscription Type**
"""

subscription_analysis['churn_rate'].plot(
    kind='bar',
    figsize=(8,5),
    title='Churn Rate by Subscription Type'
)

"""**Insight**: Free Trial users churn the most.

**2. Churn Rate by Country**
"""

country_analysis['churn_rate'].sort_values().plot(
    kind='barh',
    figsize=(8,5),
    title='Churn Rate by Country'
)

"""**Insight**: Compare churn across regions.

**3. Revenue by Acquisition Channel**
"""

channel_analysis['revenue'].sort_values(
    ascending=False
).plot(
    kind='bar',
    figsize=(8,5),
    title='Revenue by Acquisition Channel'
)

"""**Insight**: Organic and Paid Ads generate most revenue

**4. Customer Tier Distribution**
"""

customers['customer_tier'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    figsize=(6,6),
    title='Customer Tier Distribution'
)

"""**Insight**: Most customers belong to Standard tier.

**5. Top Churn Reasons**
"""

churn_reason_analysis.plot(
    kind='barh',
    figsize=(8,5),
    title='Top Reasons for Customer Churn'
)

"""**Insight**: Identifies the major causes of churn.

**6. Customer Lifetime Value (CLV) by Subscription Type**
"""

clv_analysis = subscriptions.groupby('subscription_type').agg(
    avg_clv=('lifetime_value_usd', 'mean')
).sort_values(by='avg_clv', ascending=False)

print(clv_analysis)

"""**Insight**:Premium and Pro customers generate the highest lifetime value.

**7. Revenue Loss by Subscription Type**
"""

revenue_loss = subscriptions[
    subscriptions['status'] == 'CHURNED'
].groupby('subscription_type').agg(
    revenue_lost=('monthly_price', 'sum')
).sort_values(by='revenue_lost', ascending=False)

print(revenue_loss)

"""**Insight**: Shows which plans contribute most to lost revenue.

**8. Churn Rate by Acquisition Channel**
"""

channel_churn = channel_data.groupby(
    'acquisition_channel'
).agg(
    customers=('customer_id','count'),
    churned=('status',
             lambda x:(x=='CHURNED').sum())
)

channel_churn['churn_rate'] = (
    channel_churn['churned']
    / channel_churn['customers']
) * 100

print(channel_churn)

"""**Insight**: Identify channels bringing low-quality customers.

**9. Correlation Analysis**
"""

corr = usage[
    ['engagement_score',
     'num_sessions',
     'total_hours_watched',
     'avg_session_length_min']
].corr()

print(corr)

"""**Insight**:Customers who watch more hours tend to have higher engagement.

**10. Monthly Customer Growth**
"""

monthly_growth = customers.groupby(
    customers['signup_date'].dt.to_period('M')
).agg(
    customers=('customer_id','count')
)

print(monthly_growth)

"""**Insight**: Shows customer acquisition trend over time."""